/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List All Applications
         * @description Returns a paginated list of all applications with their current status and metadata. Supports filtering by status and pagination for large datasets.
         *
         */
        get: operations["listApplications"];
        put?: never;
        /**
         * Start a New Enrolment Application
         * @description Creates a new application in a 'Draft' state. This is the new entry point for the enrolment wizard. Supports an Idempotency-Key header to prevent duplicate application creation on network retries.
         *
         */
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a Draft Application
         * @description Incrementally saves data to a draft application.
         */
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/applications/{applicationId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit an Application for Approval
         * @description Transitions the application status to 'Submitted' after validating all required data is present.
         */
        post: operations["submitApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve an Application and Create Enrolment
         * @description A protected, administrative endpoint. Takes a 'Submitted' application and executes the master transaction to create the official client, enrolment, and all associated records. This payload MUST now include the financial contract terms.
         *
         */
        post: operations["approveApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject a Submitted Application
         * @description Rejects a submitted application with a reason. This transitions the application status to 'Rejected' and prevents further processing.
         *
         */
        post: operations["rejectApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/offer-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Offer Letter
         * @description Renders an offer letter PDF from the current application snapshot and stores it in Supabase Storage.
         */
        post: operations["generateOfferLetter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/send-offer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Offer Letter
         * @description Sends the previously generated offer letter to the applicant. On success, transitions status to AwaitingPayment.
         */
        post: operations["sendOfferLetter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark an application as Accepted
         * @description Captures student acceptance (recorded by staff or callback) and transitions status to Accepted.
         */
        post: operations["acceptApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/drafts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Draft Applications
         * @description Returns a paginated list of all draft applications. This endpoint is optimized for the draft management interface.
         *
         */
        get: operations["listDraftApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/submitted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Submitted Applications
         * @description Returns a paginated list of all submitted applications awaiting approval. This endpoint is optimized for the approval workflow interface.
         *
         */
        get: operations["listSubmittedApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/approved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Approved Applications
         * @description Returns a paginated list of all approved applications. These applications have been processed and converted to enrolments.
         *
         */
        get: operations["listApprovedApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Application Statistics
         * @description Returns aggregated statistics about applications including counts by status, recent activity, and performance metrics.
         *
         */
        get: operations["getApplicationStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrolments/{enrolmentId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Change Enrolment State
         * @description Manages the lifecycle of an enrolment (Withdraw, Defer, Suspend). This is a critical, auditable state transition endpoint with compliance implications.
         *
         */
        put: operations["changeEnrolmentState"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and Search Clients */
        get: operations["listClients"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{clientId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a Single Client's Full Details
         * @description Retrieves the complete, aggregated record for a single client. The response MUST include an ETag header for concurrency control.
         *
         */
        get: operations["getClient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Client Details
         * @description Updates a subset of a client's details. Must include the If-Match header with the latest ETag to prevent lost updates. Changes to sensitive PII are auto-audited by the database.
         *
         */
        patch: operations["updateClient"];
        trace?: never;
    };
    "/clients/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Merge Two Duplicate Client Records
         * @description A protected, administrative endpoint to merge a duplicate client record into a surviving record. This is a delicate, irreversible transaction.
         */
        post: operations["mergeClients"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{clientId}/health-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check Client Data Completeness */
        get: operations["getClientHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clients/{clientId}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Notes for a Client */
        get: operations["listClientNotes"];
        put?: never;
        /** Add a Note to a Client Record */
        post: operations["createClientNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cricos/coes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Confirmation of Enrolment (CoE)
         * @description Creates a new CoE record against an enrolment, typically in a 'Draft' state before submission to PRISMS.
         */
        post: operations["createCoE"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cricos/coes/{coeId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel a Confirmation of Enrolment (CoE)
         * @description A dedicated, auditable event to cancel a CoE, with a reason code for compliance.
         */
        post: operations["cancelCoE"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrolments/{enrolmentId}/credit-transfer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Grant Credit Transfer or RPL
         * @description Formally records the granting of a credit transfer or RPL for a specific unit within an enrolment.
         */
        post: operations["createCreditTransfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrolments/{enrolmentId}/subjects/{subjectId}/outcome": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Record a Final Subject Outcome
         * @description A critical compliance endpoint. Records the final, aggregate academic outcome for a student in a specific unit of competency within an enrolment. This action is audited.
         *
         */
        put: operations["setEnrolmentSubjectOutcome"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session Roster
         * @description A user-centric endpoint that provides a simple, one-call way for a trainer to get a list of all students enrolled in their upcoming class.
         */
        get: operations["getSessionRoster"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{sessionId}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit session attendance */
        post: operations["createAttendanceSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/{staffId}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Staff Member's Schedule
         * @description A user-centric endpoint that returns a clean, aggregated list of all sessions a trainer is assigned to in a given period.
         */
        get: operations["getStaffSchedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invoices/{invoiceId}/void": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Void an Unpaid Invoice
         * @description Transitions an 'Issued' but unpaid invoice to a 'Void' state. This is for correcting errors and is illegal if a payment has been made.
         */
        post: operations["voidInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payments/{paymentId}/refund": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a Refund Against a Payment
         * @description Creates a refund record, ensuring a closed-loop accounting trail.
         */
        post: operations["refundPayment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/attendance-at-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * At-Risk Attendance Report
         * @description Returns a list of students whose attendance has fallen below a specified threshold in a given period.
         */
        get: operations["getAttendanceAtRisk"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/financial-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Financial Summary Report
         * @description Returns an aggregated financial summary for a given period.
         */
        get: operations["getFinancialSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all Programs */
        get: operations["getPrograms"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects for a Program */
        get: operations["getProgramSubjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/course-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List course plans for a program */
        get: operations["listProgramCoursePlans"];
        put?: never;
        /** Create a course plan for a program */
        post: operations["createProgramCoursePlan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/course-plans/{planId}/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get subjects for a course plan */
        get: operations["getCoursePlanSubjects"];
        /** Replace subjects for a course plan */
        put: operations["replaceCoursePlanSubjects"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course-offerings/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a course offering */
        put: operations["updateCourseOffering"];
        post?: never;
        /** Delete a course offering */
        delete: operations["deleteCourseOffering"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/payment-plan-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List payment plan templates for a program */
        get: operations["listPaymentPlanTemplates"];
        put?: never;
        /** Create a payment plan template for a program */
        post: operations["createPaymentPlanTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/payment-plan-templates/{templateId}/instalments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List instalments in a template */
        get: operations["getPaymentPlanInstalments"];
        /** Replace instalments list for a template */
        put: operations["replacePaymentPlanInstalments"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{applicationId}/derive-payment-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Derive a concrete payment schedule for an application from a template */
        post: operations["derivePaymentPlanForApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/programs/{programId}/offerings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Course Offerings for a Program
         * @description Returns available course offerings/intakes for a specific program that are open for enrolment.
         */
        get: operations["listProgramOfferings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Active Educational Agents
         * @description Returns a list of active educational agents available for student referrals.
         */
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reference-data/{codeType}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get AVETMISS Reference Codes */
        get: operations["getReferenceData"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CoursePlan: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            program_id?: string;
            name?: string;
            version?: number;
            is_active?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        CoursePlanCreate: {
            name: string;
            /** @default 1 */
            version: number;
            /** @default false */
            is_active: boolean;
        };
        CoursePlanSubject: {
            /** Format: uuid */
            subject_id?: string;
            subject_identifier?: string;
            subject_name?: string;
            /** @enum {string} */
            unit_type?: "Core" | "Elective";
            sort_order?: number;
        };
        CoursePlanSubjectInput: {
            /** Format: uuid */
            subject_id: string;
            /** @enum {string} */
            unit_type: "Core" | "Elective";
            /** @default 0 */
            sort_order: number;
        };
        CourseOfferingUpdate: {
            /** Format: uuid */
            programId?: string;
            /** Format: date */
            startDate?: string | null;
            /** Format: date */
            endDate?: string | null;
            /** Format: uuid */
            deliveryLocationId?: string | null;
            maxStudents?: number | null;
            /** @enum {string} */
            status?: "Scheduled" | "Active" | "Completed" | "Cancelled";
            isRolling?: boolean;
            /** Format: uuid */
            defaultPlanId?: string | null;
        };
        PaymentPlanTemplate: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            program_id?: string;
            name?: string;
            is_default?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        PaymentPlanTemplateCreate: {
            name: string;
            /** @default false */
            is_default: boolean;
        };
        PaymentPlanInstalment: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            template_id?: string;
            description?: string;
            /** Format: double */
            amount?: number;
            offset_days?: number;
            sort_order?: number;
        };
        PaymentPlanInstalmentInput: {
            description: string;
            /** Format: double */
            amount: number;
            /** @default 0 */
            offset_days: number;
            /** @default 0 */
            sort_order: number;
        };
        PaymentPlanDeriveInput: {
            /** Format: uuid */
            templateId: string;
            /**
             * Format: date
             * @description Deprecated; prefer anchor+anchorDate.
             */
            startDate?: string;
            /** Format: uuid */
            enrolmentId?: string | null;
            /** @enum {string} */
            anchor?: "OFFER_LETTER" | "COMMENCEMENT" | "CUSTOM";
            /**
             * Format: date
             * @description Required if anchor=CUSTOM; for COMMENCEMENT when no course offering date is set.
             */
            anchorDate?: string;
        };
        PaymentPlanDerivedInstalment: {
            description?: string;
            /** Format: double */
            amount?: number;
            /** Format: date */
            dueDate?: string;
        };
        PaymentPlanDerivedSchedule: {
            items?: components["schemas"]["PaymentPlanDerivedInstalment"][];
        };
        OfferLetterResult: {
            /** @description Storage path where the offer letter PDF is stored. */
            path?: string;
            /** @example application/pdf */
            mimeType?: string;
            sizeBytes?: number;
            version?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        /** @description The complete data object for an application. */
        FullEnrolmentPayload: {
            /** Format: uuid */
            existingClientId?: string | null;
            /** Format: uuid */
            agentId?: string | null;
            isInternationalStudent?: boolean;
            personalDetails?: components["schemas"]["ClientPersonalDetails"];
            address?: components["schemas"]["ClientAddress"];
            avetmissDetails?: components["schemas"]["ClientAvetmissDetails"];
            cricosDetails?: components["schemas"]["ClientCricosDetails"];
            usi?: components["schemas"]["ClientUSI"];
            enrolmentDetails?: components["schemas"]["EnrolmentDetails"];
            /** @description Snapshot of the selected payment plan for this draft application. */
            paymentPlan?: {
                /** Format: uuid */
                selectedTemplateId?: string;
                /** @enum {string} */
                anchor?: "OFFER_LETTER" | "COMMENCEMENT" | "CUSTOM";
                /** Format: date */
                anchorDate?: string | null;
                schedule?: components["schemas"]["PaymentPlanDerivedInstalment"][];
                /** Format: double */
                tuitionFeeSnapshot?: number;
            };
        };
        /** @description The financial contract terms agreed upon for this enrolment, submitted at the point of approval. */
        ApprovalPayload: {
            /**
             * Format: double
             * @description The agreed-upon total tuition fee for this enrolment, frozen in time.
             */
            tuitionFeeSnapshot: number;
            /**
             * Format: double
             * @description The agent's commission rate for this specific enrolment, frozen in time.
             */
            agentCommissionRateSnapshot: number;
        };
        EnrolmentDetails: {
            /** Format: uuid */
            programId?: string;
            /**
             * Format: uuid
             * @description The specific course offering/intake the student is enrolling in
             */
            courseOfferingId?: string;
            /** @description The snapshot of the program structure for this enrolment. */
            subjectStructure?: {
                coreSubjectIds?: string[];
                electiveSubjectIds?: string[];
            };
            /** Format: date */
            startDate?: string;
            /** Format: date */
            expectedCompletionDate?: string;
            /** Format: uuid */
            deliveryLocationId?: string;
            deliveryModeId?: string;
            fundingSourceId?: string;
            studyReasonId?: string;
            /** @default false */
            isVetInSchools: boolean;
        };
        FullEnrolmentResponse: {
            /** Format: uuid */
            clientId?: string;
            /** Format: uuid */
            enrolmentId?: string;
            /** @example Enrolment created successfully. */
            message?: string;
        };
        Application: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            status?: "Draft" | "Submitted" | "Approved" | "Rejected";
            application_payload?: components["schemas"]["FullEnrolmentPayload"];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        /** @description A lightweight representation of an application for list views */
        ApplicationSummary: {
            /**
             * Format: uuid
             * @description Unique identifier for the application
             */
            id?: string;
            /**
             * @description Current status of the application
             * @enum {string}
             */
            status?: "Draft" | "Submitted" | "Approved" | "Rejected";
            /**
             * @description Full name of the applicant (from personalDetails)
             * @example John Citizen
             */
            clientName?: string;
            /**
             * Format: email
             * @description Primary email of the applicant
             * @example john.citizen@example.com
             */
            clientEmail?: string;
            /**
             * @description Name of the program being applied for
             * @example Certificate III in Business
             */
            programName?: string | null;
            /**
             * @description Name of the educational agent (if applicable)
             * @example Global Education Services
             */
            agentName?: string | null;
            /**
             * Format: date-time
             * @description When the application was first created
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description When the application was last modified
             */
            updatedAt?: string;
            /**
             * Format: uuid
             * @description ID of the client created when application was approved
             */
            createdClientId?: string | null;
            /**
             * Format: uuid
             * @description ID of the enrolment created when application was approved
             */
            createdEnrolmentId?: string | null;
        };
        /** @description Paginated response for application listings */
        ApplicationListResponse: {
            data?: components["schemas"]["ApplicationSummary"][];
            pagination?: {
                /**
                 * @description Current page number (1-based)
                 * @example 1
                 */
                page?: number;
                /**
                 * @description Number of items per page
                 * @example 20
                 */
                limit?: number;
                /**
                 * @description Total number of applications matching the query
                 * @example 150
                 */
                total?: number;
                /**
                 * @description Total number of pages
                 * @example 8
                 */
                totalPages?: number;
                /**
                 * @description Whether there are more pages available
                 * @example true
                 */
                hasNext?: boolean;
                /**
                 * @description Whether there are previous pages available
                 * @example false
                 */
                hasPrevious?: boolean;
            };
        };
        EnrolmentStateChangePayload: {
            /** @enum {string} */
            status: "Withdrawn" | "Deferred" | "Suspended";
            /** Format: date */
            effectiveDate: string;
            /** @description Required if status is 'Withdrawn'. Must be a valid AVETMISS code. */
            withdrawalReasonCode?: string;
            /** @description Required if status is 'Deferred'. */
            deferralReason?: string;
            /** @description Required if status is 'Suspended'. */
            suspensionReason?: string;
            /**
             * Format: date
             * @description Required only if status is 'Deferred'.
             */
            deferralEndDate?: string;
        };
        ClientHealthStatus: {
            personalDetailsComplete?: boolean;
            avetmissComplete?: boolean;
            cricosComplete?: boolean | null;
            /** @example [
             *       "labourForceId",
             *       "highestSchoolLevelId"
             *     ] */
            missingAvetmissFields?: string[];
        };
        EnrolmentSubjectOutcomePayload: {
            /**
             * @description The final AVETMISS outcome code (e.g., 20, 30, 40).
             * @example 20
             */
            outcomeIdentifierNational: string;
            /**
             * Format: date
             * @description The actual completion date for the unit.
             */
            endDate: string;
        };
        ClientNotePayload: {
            note: string;
            category?: string | null;
        };
        CoEPayload: {
            /** Format: uuid */
            enrolmentId: string;
            /** Format: date */
            courseStartDate: string;
            /** Format: date */
            courseEndDate: string;
            /** Format: double */
            totalTuitionFee: number;
            /** Format: double */
            prepaidFees: number;
        };
        CoECancelPayload: {
            cancellationReasonCode: string;
            /** Format: date */
            effectiveDate: string;
        };
        RefundPayload: {
            /** Format: double */
            amount: number;
            refundMethod: string;
            reason?: string | null;
        };
        FinancialSummary: {
            /** Format: double */
            totalInvoiced?: number;
            /** Format: double */
            totalPaymentsReceived?: number;
            /** Format: double */
            totalRefundsIssued?: number;
            /** Format: double */
            totalCommissionsPayable?: number;
            /** Format: double */
            totalCommissionsPaid?: number;
        };
        CreditTransferPayload: {
            /** Format: uuid */
            subjectId: string;
            /** Format: date */
            grantedDate: string;
            /**
             * Format: uri
             * @description Link to the evidence document in Supabase Storage.
             */
            evidenceUrl?: string;
            issuingOrganisationName?: string;
            notes?: string | null;
        };
        ClientPersonalDetails: {
            /** @example Mr */
            title?: string;
            /** @example John */
            firstName?: string;
            /** @example Citizen */
            lastName?: string;
            /**
             * Format: date
             * @description ISO 8601 format: YYYY-MM-DD
             * @example 1990-01-15
             */
            dateOfBirth?: string;
            /**
             * @description AVETMISS code for gender
             * @example M
             */
            gender?: string;
            /**
             * Format: email
             * @example john.citizen@example.com
             */
            primaryEmail?: string;
            /** Format: email */
            alternativeEmail?: string | null;
            /** @example 0412345678 */
            mobilePhone?: string;
            homePhone?: string | null;
            workPhone?: string | null;
        };
        ClientAddress: {
            residential?: components["schemas"]["Address"];
            /** @default true */
            isPostalSameAsResidential: boolean;
            /** @description Required only if isPostalSameAsResidential is false. */
            postal?: components["schemas"]["Address"];
        };
        ClientAvetmissDetails: {
            /**
             * @description AVETMISS code for country
             * @example 1101
             */
            countryOfBirthId?: string;
            /**
             * @description AVETMISS code for language
             * @example 1201
             */
            languageAtHomeId?: string;
            /**
             * @description AVETMISS code for indigenous status
             * @example 4
             */
            indigenousStatusId?: string;
            /**
             * @description AVETMISS code for school level
             * @example 12
             */
            highestSchoolLevelId?: string;
            isAtSchool?: boolean;
            hasDisability?: boolean;
            disabilityTypeIds?: string[];
            hasPriorEducation?: boolean;
            priorEducationCodes?: string[];
            /**
             * @description AVETMISS code for labour force status
             * @example 03
             */
            labourForceId?: string;
            /**
             * @description AVETMISS code for survey status
             * @example A
             */
            surveyContactStatus?: string | null;
        };
        ClientCricosDetails: {
            /**
             * @description ISO 3166-1 alpha-3 country code
             * @example AUS
             */
            countryOfCitizenshipId?: string;
            /** @example E1234567 */
            passportNumber?: string;
            /**
             * Format: date
             * @example 2030-01-01
             */
            passportExpiryDate?: string;
        };
        /** @description Exactly one of usi or exemptionCode must be provided. */
        ClientUSI: {
            /** @example 3AW88WHM8G */
            usi?: string | null;
            /**
             * @description AVETMISS code for USI exemption
             * @example INT
             */
            exemptionCode?: string | null;
        };
        Address: {
            /** @example 123 */
            streetNumber?: string;
            /** @example Main Street */
            streetName?: string;
            /** @example Unit 5 */
            unitDetails?: string | null;
            buildingName?: string | null;
            /** @example Sydney */
            suburb?: string;
            /** @example NSW */
            state?: string;
            /** @example 2000 */
            postcode?: string;
        };
        ErrorResponse: {
            /** @example Validation failed */
            message?: string;
            errors?: {
                /** @example personalDetails.dateOfBirth */
                field?: string;
                /** @example Date of birth cannot be in the future. */
                message?: string;
            }[];
        };
        AttendanceSubmission: {
            /** Format: uuid */
            clientId: string;
            /** @enum {string} */
            status: "Present" | "Absent" | "Late" | "Excused";
            notes?: string | null;
        };
        GradePayload: {
            /** @enum {string} */
            grade: "C" | "NYC";
            feedback?: string | null;
        };
        PaymentPayload: {
            /**
             * Format: double
             * @description The amount of the payment received.
             */
            amount: number;
            /** @enum {string} */
            paymentMethod: "Credit Card" | "Bank Transfer" | "Cash" | "Other";
            /** Format: date */
            paymentDate?: string;
            /** @description e.g., Stripe transaction ID */
            transactionReference?: string | null;
        };
        ClientFull: {
            /** Format: uuid */
            readonly id?: string;
            readonly clientIdentifier?: string;
            personalDetails?: components["schemas"]["ClientPersonalDetails"];
            address?: components["schemas"]["ClientAddress"];
            avetmissDetails?: components["schemas"]["ClientAvetmissDetails"];
            cricosDetails?: components["schemas"]["ClientCricosDetails"];
            usi?: components["schemas"]["ClientUSI"];
            /** Format: date-time */
            readonly createdAt?: string;
            /** Format: date-time */
            readonly updatedAt?: string;
        };
        ClientSummary: {
            /** Format: uuid */
            id?: string;
            clientIdentifier?: string;
            firstName?: string;
            lastName?: string;
            /** Format: email */
            primaryEmail?: string;
            mobilePhone?: string;
        };
        Payment: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly invoiceId?: string;
            /** Format: double */
            readonly amount?: number;
            /** Format: date */
            readonly paymentDate?: string;
            readonly paymentMethod?: string;
            readonly transactionReference?: string | null;
            /** Format: date-time */
            readonly createdAt?: string;
        };
        AssessmentSubmission: {
            /** Format: uuid */
            readonly id?: string;
            /** Format: uuid */
            readonly assessmentTaskId?: string;
            /** Format: uuid */
            readonly clientId?: string;
            readonly attemptNumber?: number;
            /** Format: date-time */
            readonly submissionDate?: string;
            /** @enum {string|null} */
            grade?: "C" | "NYC" | null;
            /** Format: date-time */
            readonly gradedAt?: string | null;
            feedback?: string | null;
        };
        Program: {
            /** Format: uuid */
            id?: string;
            program_identifier?: string;
            program_name?: string;
            status?: string;
        };
        ProgramSubject: {
            /** Format: uuid */
            subject_id?: string;
            subject_identifier?: string;
            subject_name?: string;
            /** @enum {string} */
            unit_type?: "Core" | "Elective";
        };
        ReferenceCode: {
            /** @example 1101 */
            code?: string;
            /** @example Australia */
            description?: string;
        };
        Agent: {
            /** Format: uuid */
            id?: string;
            /** @example Global Education Services */
            agent_name?: string;
            /** @example International */
            agent_type?: string;
            /** @example John Smith */
            primary_contact_name?: string | null;
            /**
             * Format: email
             * @example john@globaledu.com
             */
            primary_contact_email?: string;
            /** @example +61 2 1234 5678 */
            primary_contact_phone?: string | null;
            /** @example Active */
            status?: string;
            /**
             * Format: double
             * @example 15
             */
            commission_rate?: number | null;
        };
        CourseOffering: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            program_id?: string;
            /** Format: date */
            start_date?: string;
            /** Format: date */
            end_date?: string;
            /** Format: uuid */
            delivery_location_id?: string | null;
            max_students?: number | null;
            /** @enum {string} */
            status?: "Scheduled" | "Active" | "Completed" | "Cancelled";
        };
    };
    responses: {
        /** @description Bad Request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        ApplicationId: string;
        EnrolmentId: string;
        ClientId: string;
        SubjectId: string;
        CoEId: string;
        SessionId: string;
        SubmissionId: string;
        InvoiceId: string;
        PaymentId: string;
        ProgramId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listApplications: {
        parameters: {
            query?: {
                /** @description Page number for pagination (1-based) */
                page?: number;
                /** @description Number of applications per page */
                limit?: number;
                /** @description Filter applications by status */
                status?: "Draft" | "Submitted" | "Approved" | "Rejected";
                /** @description Search applications by client name or email */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paginated list of applications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationListResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Can be an empty body to create a blank draft, or can contain initial data. */
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FullEnrolmentPayload"];
            };
        };
        responses: {
            /** @description Draft application created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["FullEnrolmentPayload"];
            };
        };
        responses: {
            /** @description Application updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    submitApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application submitted for review. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    approveApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalPayload"];
            };
        };
        responses: {
            /** @description Application approved and enrolment created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FullEnrolmentResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    rejectApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Reason for rejection */
                    reason: string;
                };
            };
        };
        responses: {
            /** @description Application rejected successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    generateOfferLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offer letter generated and stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfferLetterResult"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    sendOfferLetter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offer letter sent and status transitioned. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    acceptApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application accepted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        message?: string;
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listDraftApplications: {
        parameters: {
            query?: {
                /** @description Page number for pagination (1-based) */
                page?: number;
                /** @description Number of applications per page */
                limit?: number;
                /** @description Search applications by client name or email */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paginated list of draft applications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listSubmittedApplications: {
        parameters: {
            query?: {
                /** @description Page number for pagination (1-based) */
                page?: number;
                /** @description Number of applications per page */
                limit?: number;
                /** @description Search applications by client name or email */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paginated list of submitted applications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listApprovedApplications: {
        parameters: {
            query?: {
                /** @description Page number for pagination (1-based) */
                page?: number;
                /** @description Number of applications per page */
                limit?: number;
                /** @description Search applications by client name or email */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A paginated list of approved applications. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getApplicationStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application statistics. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    changeEnrolmentState: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrolmentId: components["parameters"]["EnrolmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrolmentStateChangePayload"];
            };
        };
        responses: {
            /** @description Enrolment state successfully changed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listClients: {
        parameters: {
            query?: {
                search?: string;
                page?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of clients. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientSummary"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getClient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The full client record. */
            200: {
                headers: {
                    /** @description The current version identifier for the client record. */
                    ETag?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientFull"];
                };
            };
            /** @description Client not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateClient: {
        parameters: {
            query?: never;
            header: {
                /** @description The ETag value from the last GET request. */
                "If-Match": string;
            };
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientPersonalDetails"];
            };
        };
        responses: {
            /** @description Client updated successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientFull"];
                };
            };
            /** @description Client not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Precondition Failed. The client record was modified by someone else. */
            412: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    mergeClients: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    survivingClientId?: string;
                    /** Format: uuid */
                    subsumedClientId?: string;
                };
            };
        };
        responses: {
            /** @description Merge successful. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getClientHealth: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Health status retrieved successfully. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientHealthStatus"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Client not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listClientNotes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of notes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createClientNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: components["parameters"]["ClientId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientNotePayload"];
            };
        };
        responses: {
            /** @description Note created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createCoE: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoEPayload"];
            };
        };
        responses: {
            /** @description CoE created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    cancelCoE: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                coeId: components["parameters"]["CoEId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoECancelPayload"];
            };
        };
        responses: {
            /** @description CoE cancelled. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createCreditTransfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrolmentId: components["parameters"]["EnrolmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreditTransferPayload"];
            };
        };
        responses: {
            /** @description Credit transfer successfully granted and recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    setEnrolmentSubjectOutcome: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrolmentId: components["parameters"]["EnrolmentId"];
                subjectId: components["parameters"]["SubjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrolmentSubjectOutcomePayload"] | components["schemas"]["GradePayload"];
            };
        };
        responses: {
            /** @description Outcome successfully recorded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getSessionRoster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The class roster. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createAttendanceSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AttendanceSubmission"];
            };
        };
        responses: {
            /** @description Attendance recorded. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getStaffSchedule: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
            };
            header?: never;
            path: {
                staffId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The staff member's schedule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    voidInvoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invoiceId: components["parameters"]["InvoiceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invoice successfully voided. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    refundPayment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                paymentId: components["parameters"]["PaymentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefundPayload"] | components["schemas"]["PaymentPayload"];
            };
        };
        responses: {
            /** @description Refund processed. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getAttendanceAtRisk: {
        parameters: {
            query: {
                minPercentage: number;
                startDate?: string;
                endDate?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of at-risk students. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getFinancialSummary: {
        parameters: {
            query: {
                startDate: string;
                endDate: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated financial data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinancialSummary"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getPrograms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of programs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Program"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getProgramSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of subjects for the program. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgramSubject"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listProgramCoursePlans: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of course plans */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePlan"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createProgramCoursePlan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoursePlanCreate"];
            };
        };
        responses: {
            /** @description Course plan created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePlan"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getCoursePlanSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subjects in the plan */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePlanSubject"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    replaceCoursePlanSubjects: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoursePlanSubjectInput"][];
            };
        };
        responses: {
            /** @description Plan subjects updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCourseOffering: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseOfferingUpdate"];
            };
        };
        responses: {
            /** @description Offering updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteCourseOffering: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Offering deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listPaymentPlanTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of payment plan templates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentPlanTemplate"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    createPaymentPlanTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentPlanTemplateCreate"];
            };
        };
        responses: {
            /** @description Template created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentPlanTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getPaymentPlanInstalments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instalments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentPlanInstalment"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    replacePaymentPlanInstalments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                templateId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentPlanInstalmentInput"][];
            };
        };
        responses: {
            /** @description Instalments updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    derivePaymentPlanForApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: components["parameters"]["ApplicationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentPlanDeriveInput"];
            };
        };
        responses: {
            /** @description Derived schedule */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentPlanDerivedSchedule"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listProgramOfferings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                programId: components["parameters"]["ProgramId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of course offerings for the program. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseOffering"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listAgents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of active agents. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    getReferenceData: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                codeType: "COUNTRY" | "LANGUAGE" | "DISABILITY_TYPE" | "PRIOR_EDUCATION" | "FUNDING_SOURCE" | "STUDY_REASON";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description A list of code-value pairs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceCode"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
}
