/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

// Buffer polyfill for Deno
declare global {
  interface Buffer {
    toString(): string;
  }
}

export type AuthAalLevel = "aal1" | "aal2" | "aal3";

export type AuthCodeChallengeMethod = "plain" | "s256";

export type AuthFactorStatus = "unverified" | "verified";

export type AuthFactorType = "phone" | "totp" | "webauthn";

export type AuthOauthRegistrationType = "dynamic" | "manual";

export type AuthOneTimeTokenType = "confirmation_token" | "email_change_token_current" | "email_change_token_new" | "phone_change_token" | "reauthentication_token" | "recovery_token";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type SmsOpInstalmentAnchor = "commencement_date" | "custom_date" | "enrolment_date";

export type StorageBuckettype = "ANALYTICS" | "STANDARD";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface _RealtimeExtensions {
  id: string;
  inserted_at: Timestamp;
  settings: Json | null;
  tenant_external_id: string | null;
  type: string | null;
  updated_at: Timestamp;
}

export interface _RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface _RealtimeTenants {
  broadcast_adapter: Generated<string | null>;
  external_id: string | null;
  id: string;
  inserted_at: Timestamp;
  jwt_jwks: Json | null;
  jwt_secret: string | null;
  max_bytes_per_second: Generated<number>;
  max_channels_per_client: Generated<number>;
  max_concurrent_users: Generated<number>;
  max_events_per_second: Generated<number>;
  max_joins_per_second: Generated<number>;
  max_payload_size_in_kb: Generated<number | null>;
  max_presence_events_per_second: Generated<number | null>;
  migrations_ran: Generated<number | null>;
  name: string | null;
  notify_private_alpha: Generated<boolean | null>;
  postgres_cdc_default: Generated<string | null>;
  private_only: Generated<boolean>;
  suspend: Generated<boolean | null>;
  updated_at: Timestamp;
}

export interface AuthAuditLogEntries {
  created_at: Timestamp | null;
  id: string;
  instance_id: string | null;
  ip_address: Generated<string>;
  payload: Json | null;
}

export interface AuthFlowState {
  auth_code: string;
  auth_code_issued_at: Timestamp | null;
  authentication_method: string;
  code_challenge: string;
  code_challenge_method: AuthCodeChallengeMethod;
  created_at: Timestamp | null;
  id: string;
  provider_access_token: string | null;
  provider_refresh_token: string | null;
  provider_type: string;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthIdentities {
  created_at: Timestamp | null;
  /**
   * Auth: Email is a generated column that references the optional email property in the identity_data
   */
  email: Generated<string | null>;
  id: Generated<string>;
  identity_data: Json;
  last_sign_in_at: Timestamp | null;
  provider: string;
  provider_id: string;
  updated_at: Timestamp | null;
  user_id: string;
}

export interface AuthInstances {
  created_at: Timestamp | null;
  id: string;
  raw_base_config: string | null;
  updated_at: Timestamp | null;
  uuid: string | null;
}

export interface AuthMfaAmrClaims {
  authentication_method: string;
  created_at: Timestamp;
  id: string;
  session_id: string;
  updated_at: Timestamp;
}

export interface AuthMfaChallenges {
  created_at: Timestamp;
  factor_id: string;
  id: string;
  ip_address: string;
  otp_code: string | null;
  verified_at: Timestamp | null;
  web_authn_session_data: Json | null;
}

export interface AuthMfaFactors {
  created_at: Timestamp;
  factor_type: AuthFactorType;
  friendly_name: string | null;
  id: string;
  last_challenged_at: Timestamp | null;
  phone: string | null;
  secret: string | null;
  status: AuthFactorStatus;
  updated_at: Timestamp;
  user_id: string;
  web_authn_aaguid: string | null;
  web_authn_credential: Json | null;
}

export interface AuthOauthClients {
  client_id: string;
  client_name: string | null;
  client_secret_hash: string;
  client_uri: string | null;
  created_at: Generated<Timestamp>;
  deleted_at: Timestamp | null;
  grant_types: string;
  id: string;
  logo_uri: string | null;
  redirect_uris: string;
  registration_type: AuthOauthRegistrationType;
  updated_at: Generated<Timestamp>;
}

export interface AuthOneTimeTokens {
  created_at: Generated<Timestamp>;
  id: string;
  relates_to: string;
  token_hash: string;
  token_type: AuthOneTimeTokenType;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface AuthRefreshTokens {
  created_at: Timestamp | null;
  id: Generated<Int8>;
  instance_id: string | null;
  parent: string | null;
  revoked: boolean | null;
  session_id: string | null;
  token: string | null;
  updated_at: Timestamp | null;
  user_id: string | null;
}

export interface AuthSamlProviders {
  attribute_mapping: Json | null;
  created_at: Timestamp | null;
  entity_id: string;
  id: string;
  metadata_url: string | null;
  metadata_xml: string;
  name_id_format: string | null;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSamlRelayStates {
  created_at: Timestamp | null;
  flow_state_id: string | null;
  for_email: string | null;
  id: string;
  redirect_to: string | null;
  request_id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSchemaMigrations {
  version: string;
}

export interface AuthSessions {
  aal: AuthAalLevel | null;
  created_at: Timestamp | null;
  factor_id: string | null;
  id: string;
  ip: string | null;
  /**
   * Auth: Not after is a nullable column that contains a timestamp after which the session should be regarded as expired.
   */
  not_after: Timestamp | null;
  refreshed_at: Timestamp | null;
  tag: string | null;
  updated_at: Timestamp | null;
  user_agent: string | null;
  user_id: string;
}

export interface AuthSsoDomains {
  created_at: Timestamp | null;
  domain: string;
  id: string;
  sso_provider_id: string;
  updated_at: Timestamp | null;
}

export interface AuthSsoProviders {
  created_at: Timestamp | null;
  disabled: boolean | null;
  id: string;
  /**
   * Auth: Uniquely identifies a SSO provider according to a user-chosen resource ID (case insensitive), useful in infrastructure as code.
   */
  resource_id: string | null;
  updated_at: Timestamp | null;
}

export interface AuthUsers {
  aud: string | null;
  banned_until: Timestamp | null;
  confirmation_sent_at: Timestamp | null;
  confirmation_token: string | null;
  confirmed_at: Generated<Timestamp | null>;
  created_at: Timestamp | null;
  deleted_at: Timestamp | null;
  email: string | null;
  email_change: string | null;
  email_change_confirm_status: Generated<number | null>;
  email_change_sent_at: Timestamp | null;
  email_change_token_current: Generated<string | null>;
  email_change_token_new: string | null;
  email_confirmed_at: Timestamp | null;
  encrypted_password: string | null;
  id: string;
  instance_id: string | null;
  invited_at: Timestamp | null;
  is_anonymous: Generated<boolean>;
  /**
   * Auth: Set this column to true when the account comes from SSO. These accounts can have duplicate emails.
   */
  is_sso_user: Generated<boolean>;
  is_super_admin: boolean | null;
  last_sign_in_at: Timestamp | null;
  phone: Generated<string | null>;
  phone_change: Generated<string | null>;
  phone_change_sent_at: Timestamp | null;
  phone_change_token: Generated<string | null>;
  phone_confirmed_at: Timestamp | null;
  raw_app_meta_data: Json | null;
  raw_user_meta_data: Json | null;
  reauthentication_sent_at: Timestamp | null;
  reauthentication_token: Generated<string | null>;
  recovery_sent_at: Timestamp | null;
  recovery_token: string | null;
  role: string | null;
  updated_at: Timestamp | null;
}

export interface AvetmissClientAvetmissDetails {
  at_school_flag: Generated<string>;
  client_id: string;
  disability_flag: Generated<string>;
  highest_school_level_completed_identifier: string;
  indigenous_status_identifier: string;
  labour_force_status_identifier: string;
  language_identifier: string;
  prior_educational_achievement_flag: Generated<string>;
  survey_contact_status: string | null;
}

export interface AvetmissClientDisabilities {
  client_id: string;
  disability_type_identifier: string;
  id: Generated<string>;
}

export interface AvetmissClientPriorAchievements {
  client_id: string;
  id: Generated<string>;
  prior_educational_achievement_identifier: string;
}

export interface AvetmissCodes {
  avetmiss_version: Generated<string | null>;
  code_description: string;
  code_type: string;
  code_value: string;
  id: Generated<string>;
  is_active: Generated<boolean | null>;
  sort_order: Generated<number | null>;
}

export interface AvetmissProgramAvetmissDetails {
  anzsco_identifier: string | null;
  nominal_hours: number;
  program_field_of_education_identifier: string | null;
  program_id: string;
  program_level_of_education_identifier: string | null;
  program_recognition_identifier: string | null;
  vet_flag: string | null;
}

export interface AvetmissProgramCompletions {
  client_id: string;
  date_program_completed: Timestamp;
  id: Generated<string>;
  issued_flag: string;
  parchment_issue_date: Timestamp | null;
  parchment_number: string | null;
  program_id: string;
  training_organisation_id: string;
}

export interface AvetmissSubjectAvetmissDetails {
  nominal_hours: number | null;
  subject_field_of_education_identifier: string | null;
  subject_id: string;
  vet_flag: string | null;
}

export interface AvetmissSubmissionsSnapshotNat00010 {
  submission_id: string;
  training_organisation_identifier: string | null;
  training_organisation_name: string | null;
}

export interface AvetmissSubmissionsSnapshotNat00020 {
  country_identifier: string | null;
  id: Generated<string>;
  postcode: string | null;
  state_identifier: string | null;
  submission_id: string;
  suburb: string | null;
  training_organisation_delivery_location_identifier: string | null;
  training_organisation_delivery_location_name: string | null;
  training_organisation_identifier: string | null;
}

export interface AvetmissSubmissionsSnapshotNat00120 {
  activity_end_date: string | null;
  activity_start_date: string | null;
  client_identifier: string | null;
  delivery_mode_identifier: string | null;
  funding_source_national: string | null;
  id: Generated<string>;
  outcome_identifier_national: string | null;
  program_identifier: string | null;
  subject_identifier: string | null;
  submission_id: string;
  training_organisation_identifier: string | null;
}

export interface AvetmissSubmissionsSubmissions {
  /**
   * If this is a correction, this points to the submission ID it replaces.
   */
  amends_submission_id: string | null;
  /**
   * URL/path to the uploaded AVS error report for this submission draft.
   */
  avs_error_report_url: string | null;
  contact_staff_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  organisation_id: string;
  reporting_year: number;
  status: Generated<string>;
  submission_type: Generated<string>;
  submitted_at: Timestamp | null;
}

export interface AvetmissTrainingActivities {
  activity_end_date: Timestamp;
  activity_start_date: Timestamp;
  client_id: string;
  client_identifier_apprenticeships: string | null;
  commencing_program_identifier: string | null;
  delivery_location_id: string;
  delivery_mode_identifier: string;
  funding_source_national: string;
  id: Generated<string>;
  outcome_identifier_national: string;
  program_id: string | null;
  school_type_identifier: string | null;
  specific_funding_identifier: string | null;
  state_specific_data: Json | null;
  study_reason_identifier: string | null;
  subject_id: string;
  training_contract_identifier: string | null;
  training_organisation_id: string;
  vet_in_schools_flag: Generated<string>;
}

export interface CoreAddresses {
  address_line_1: string | null;
  address_line_2: string | null;
  building_property_name: string | null;
  country_identifier: Generated<string>;
  created_at: Generated<Timestamp | null>;
  flat_unit_details: string | null;
  id: Generated<string>;
  postcode: string;
  sa1_identifier: string | null;
  sa2_identifier: string | null;
  state_identifier: string;
  street_name: string | null;
  street_number: string | null;
  suburb: string;
  updated_at: Generated<Timestamp | null>;
}

export interface CoreAgents {
  abn: string | null;
  address_id: string | null;
  agent_name: string;
  agent_type: string;
  agreement_end_date: Timestamp | null;
  agreement_start_date: Timestamp | null;
  commission_rate: Generated<Numeric | null>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  primary_contact_email: string;
  primary_contact_name: string | null;
  primary_contact_phone: string | null;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface CoreClientAddresses {
  address_id: string;
  address_type: string;
  client_id: string;
}

export interface CoreClientNotes {
  category: string | null;
  client_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  note: string;
  staff_id: string | null;
}

export interface CoreClients {
  client_identifier: string;
  country_of_birth_identifier: string | null;
  created_at: Generated<Timestamp | null>;
  date_of_birth: Timestamp;
  first_name: string;
  gender: string;
  id: Generated<string>;
  last_name: string;
  middle_name: string | null;
  primary_email: string | null;
  primary_phone: string | null;
  title: string | null;
  unique_student_identifier: string | null;
  updated_at: Generated<Timestamp | null>;
  usi_verification_status: Generated<string | null>;
  usi_verified_at: Timestamp | null;
}

export interface CoreClientsAudit {
  changed_at: Generated<Timestamp>;
  changed_by_staff_id: string | null;
  changed_column: string;
  client_id: string;
  id: Generated<Int8>;
  new_value: string | null;
  old_value: string | null;
}

export interface CoreLocations {
  address_id: string;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  /**
   * Indicates if the location is active for training delivery
   */
  is_active: Generated<boolean | null>;
  location_identifier: string;
  location_name: string;
  organisation_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface CoreOrganisations {
  /**
   * Reference to core.addresses table for NAT00010 address information
   */
  address_id: string | null;
  /**
   * NAT00010: Contact name (A, 60)
   */
  contact_name: string | null;
  created_at: Generated<Timestamp | null>;
  /**
   * NAT00010: Email address (A, 80)
   */
  email_address: string | null;
  /**
   * NAT00010: Facsimile number (A, 20)
   */
  fax_number: string | null;
  id: Generated<string>;
  organisation_identifier: string;
  organisation_name: string;
  organisation_type_identifier: string | null;
  /**
   * NAT00010: Telephone number (A, 20)
   */
  phone_number: string | null;
  /**
   * AVETMISS State Identifier (e.g., VIC, NSW). Governs state-specific reporting logic.
   */
  state_identifier: Generated<string>;
  updated_at: Generated<Timestamp | null>;
}

export interface CoreProgramCoursePlans {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  program_id: string;
  version: Generated<number>;
}

export interface CoreProgramCoursePlanSubjects {
  /**
   * Difficulty level of the subject content
   */
  complexity_level: Generated<string | null>;
  /**
   * Estimated time to complete this subject in weeks
   */
  estimated_duration_weeks: Generated<number | null>;
  plan_id: string;
  sort_order: Generated<number>;
  subject_id: string;
  unit_type: string;
}

export interface CorePrograms {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  program_identifier: string;
  program_name: string;
  status: Generated<string>;
  tga_url: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface CoreProgramSchedules {
  created_at: Generated<Timestamp>;
  cycle_anchor_date: Timestamp;
  id: Generated<string>;
  name: Generated<string>;
  program_id: string;
  timezone: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface CoreProgramScheduleUnits {
  created_at: Generated<Timestamp>;
  duration_days: number;
  id: Generated<string>;
  order_index: number;
  schedule_id: string;
  subject_id: string;
  updated_at: Generated<Timestamp>;
}

export interface CoreProgramSubjects {
  created_at: Generated<Timestamp>;
  elective_group: string | null;
  program_id: string;
  subject_id: string;
  unit_type: string;
}

export interface CoreSubjectPrerequisites {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  prerequisite_subject_id: string;
  /**
   * Required: Must be completed before subject can start. Recommended: Suggested but not mandatory
   */
  prerequisite_type: string;
  subject_id: string;
}

export interface CoreSubjects {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  status: Generated<string>;
  subject_identifier: string;
  subject_name: string;
  tga_url: string | null;
  updated_at: Generated<Timestamp | null>;
}

export interface CricosClientDetails {
  client_id: string;
  country_of_citizenship_id: string;
  created_at: Generated<Timestamp>;
  oshc_paid_to_date: Timestamp | null;
  oshc_policy_number: string | null;
  oshc_provider: string | null;
  passport_expiry_date: Timestamp;
  /**
   * CRITICAL PII. This data MUST be encrypted at the application layer before being stored.
   */
  passport_number: string;
  updated_at: Generated<Timestamp>;
  visa_expiry_date: Timestamp | null;
  visa_grant_number: string | null;
  visa_subclass: string | null;
}

export interface CricosConfirmationsOfEnrolment {
  cancellation_reason_code: string | null;
  cancelled_at: Timestamp | null;
  coe_identifier: string | null;
  course_end_date: Timestamp;
  course_start_date: Timestamp;
  created_at: Generated<Timestamp>;
  enrolment_id: string;
  id: Generated<string>;
  issued_at: Timestamp | null;
  prepaid_fees: Numeric;
  prisms_payload: Json | null;
  status: Generated<string>;
  total_tuition_fee: Numeric;
  updated_at: Generated<Timestamp>;
}

export interface ExtensionsPgStatStatements {
  calls: Int8 | null;
  dbid: number | null;
  jit_deform_count: Int8 | null;
  jit_deform_time: number | null;
  jit_emission_count: Int8 | null;
  jit_emission_time: number | null;
  jit_functions: Int8 | null;
  jit_generation_time: number | null;
  jit_inlining_count: Int8 | null;
  jit_inlining_time: number | null;
  jit_optimization_count: Int8 | null;
  jit_optimization_time: number | null;
  local_blk_read_time: number | null;
  local_blk_write_time: number | null;
  local_blks_dirtied: Int8 | null;
  local_blks_hit: Int8 | null;
  local_blks_read: Int8 | null;
  local_blks_written: Int8 | null;
  max_exec_time: number | null;
  max_plan_time: number | null;
  mean_exec_time: number | null;
  mean_plan_time: number | null;
  min_exec_time: number | null;
  min_plan_time: number | null;
  minmax_stats_since: Timestamp | null;
  plans: Int8 | null;
  query: string | null;
  queryid: Int8 | null;
  rows: Int8 | null;
  shared_blk_read_time: number | null;
  shared_blk_write_time: number | null;
  shared_blks_dirtied: Int8 | null;
  shared_blks_hit: Int8 | null;
  shared_blks_read: Int8 | null;
  shared_blks_written: Int8 | null;
  stats_since: Timestamp | null;
  stddev_exec_time: number | null;
  stddev_plan_time: number | null;
  temp_blk_read_time: number | null;
  temp_blk_write_time: number | null;
  temp_blks_read: Int8 | null;
  temp_blks_written: Int8 | null;
  toplevel: boolean | null;
  total_exec_time: number | null;
  total_plan_time: number | null;
  userid: number | null;
  wal_bytes: Numeric | null;
  wal_fpi: Int8 | null;
  wal_records: Int8 | null;
}

export interface ExtensionsPgStatStatementsInfo {
  dealloc: Int8 | null;
  stats_reset: Timestamp | null;
}

export interface NetHttpRequestQueue {
  body: Buffer | null;
  headers: Json;
  id: Generated<Int8>;
  method: string;
  timeout_milliseconds: number;
  url: string;
}

export interface NetHttpResponse {
  content: string | null;
  content_type: string | null;
  created: Generated<Timestamp>;
  error_msg: string | null;
  headers: Json | null;
  id: Int8 | null;
  status_code: number | null;
  timed_out: boolean | null;
}

export interface RealtimeMessages {
  event: string | null;
  extension: string;
  id: Generated<string>;
  inserted_at: Generated<Timestamp>;
  payload: Json | null;
  private: Generated<boolean | null>;
  topic: string;
  updated_at: Generated<Timestamp>;
}

export interface RealtimeSchemaMigrations {
  inserted_at: Timestamp | null;
  version: Int8;
}

export interface RealtimeSubscription {
  claims: Json;
  claims_role: Generated<string>;
  created_at: Generated<Timestamp>;
  entity: string;
  filters: Generated<string[]>;
  id: Generated<Int8>;
  subscription_id: string;
}

export interface SecurityRoles {
  id: Generated<Int8>;
  name: string;
}

export interface SecurityUserRoles {
  role_id: Int8;
  user_id: string;
}

export interface SecurityUsers {
  avatar_url: string | null;
  client_id: string | null;
  full_name: string | null;
  id: string;
  staff_id: string | null;
}

export interface SmsOpAgentCommissions {
  agent_id: string;
  commission_amount: Numeric;
  commission_rate_snapshot: Numeric;
  id: Generated<string>;
  paid_date: Timestamp | null;
  payment_id: string;
  status: Generated<string>;
}

export interface SmsOpApplicationDocuments {
  application_id: string;
  created_at: Generated<Timestamp>;
  doc_type: string;
  id: Generated<string>;
  mime_type: string | null;
  path: string;
  size_bytes: Int8 | null;
  version: string | null;
}

export interface SmsOpApplications {
  agent_commission_rate_snapshot: Numeric | null;
  application_payload: Json | null;
  created_at: Generated<Timestamp>;
  created_by_staff_id: string | null;
  created_client_id: string | null;
  created_enrolment_id: string | null;
  id: Generated<string>;
  payment_anchor: string | null;
  payment_anchor_date: Timestamp | null;
  payment_snapshot: Json | null;
  selected_payment_template_id: string | null;
  status: Generated<string>;
  tuition_fee_snapshot: Numeric | null;
  updated_at: Generated<Timestamp>;
}

export interface SmsOpAssessmentSubmissions {
  assessment_task_id: string;
  attempt_number: Generated<number>;
  client_id: string;
  feedback: string | null;
  grade: string | null;
  graded_at: Timestamp | null;
  graded_by_staff_id: string | null;
  id: Generated<string>;
  submission_date: Generated<Timestamp>;
}

export interface SmsOpAssessmentTasks {
  created_at: Generated<Timestamp>;
  description: string | null;
  due_date: Timestamp | null;
  id: Generated<string>;
  subject_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
}

export interface SmsOpCourseOfferings {
  created_at: Generated<Timestamp | null>;
  default_plan_id: string | null;
  delivery_location_id: string | null;
  end_date: Timestamp | null;
  id: Generated<string>;
  is_rolling: Generated<boolean>;
  max_students: number | null;
  program_id: string;
  schedule_id: string | null;
  start_date: Timestamp | null;
  status: Generated<string>;
  term_index: number | null;
  trainer_id: string | null;
}

export interface SmsOpEnrolments {
  /**
   * The agent's commission rate at the exact moment of enrolment, frozen in time.
   */
  agent_commission_rate_snapshot: Numeric | null;
  agent_id: string | null;
  client_id: string;
  client_identifier_apprenticeships: string | null;
  course_offering_id: string;
  created_at: Generated<Timestamp | null>;
  deferral_end_date: Timestamp | null;
  deferral_start_date: Timestamp | null;
  enrolment_date: Generated<Timestamp>;
  id: Generated<string>;
  school_type_identifier: string | null;
  specific_funding_identifier: string | null;
  status: Generated<string>;
  training_contract_identifier: string | null;
  /**
   * The total tuition fee for this enrolment at the moment it was created, frozen in time.
   */
  tuition_fee_snapshot: Numeric | null;
  vet_in_schools_flag: Generated<boolean>;
  withdrawal_reason: string | null;
}

export interface SmsOpEnrolmentSubjectOutcomes {
  created_at: Generated<Timestamp>;
  end_date: Timestamp;
  enrolment_id: string;
  id: Generated<string>;
  outcome_identifier_national: string;
  recorded_by_staff_id: string | null;
  start_date: Timestamp;
  subject_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SmsOpEnrolmentSubjects {
  created_at: Generated<Timestamp>;
  enrolment_id: string;
  id: Generated<string>;
  subject_id: string;
  unit_type: string;
}

export interface SmsOpInvoiceLineItems {
  description: string;
  id: Generated<string>;
  invoice_id: string;
  quantity: Generated<number>;
  total_price: Numeric;
  unit_price: Numeric;
}

export interface SmsOpInvoices {
  amount_paid: Generated<Numeric>;
  created_at: Generated<Timestamp | null>;
  due_date: Timestamp;
  enrolment_id: string;
  id: Generated<string>;
  invoice_number: string;
  issue_date: Generated<Timestamp>;
  notes: string | null;
  status: Generated<string>;
  total_amount: Numeric;
}

export interface SmsOpOutcomesAudit {
  changed_at: Generated<Timestamp>;
  changed_by_staff_id: string | null;
  enrolment_id: string;
  id: Generated<Int8>;
  new_end_date: Timestamp | null;
  new_outcome_identifier: string | null;
  old_end_date: Timestamp | null;
  old_outcome_identifier: string | null;
  outcome_id: string;
  subject_id: string;
}

export interface SmsOpPaymentPlanInstalments {
  amount_due: Numeric;
  due_date: Timestamp;
  generated_invoice_id: string | null;
  id: Generated<string>;
  payment_plan_id: string;
  status: Generated<string>;
}

export interface SmsOpPaymentPlans {
  enrolment_id: string;
  frequency: string;
  id: Generated<string>;
  number_of_instalments: number;
  start_date: Timestamp;
  status: Generated<string>;
  total_amount: Numeric;
}

export interface SmsOpPaymentPlanTemplateInstalments {
  amount: Numeric;
  description: string;
  id: Generated<string>;
  offset_days: Generated<number>;
  sort_order: Generated<number>;
  template_id: string;
}

export interface SmsOpPaymentPlanTemplates {
  /**
   * Defines what date the offset_days in instalments are calculated from
   */
  anchor_type: Generated<SmsOpInstalmentAnchor>;
  created_at: Generated<Timestamp>;
  /**
   * Custom date to use when anchor_type is custom_date
   */
  custom_anchor_date: Timestamp | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  name: string;
  program_id: string;
}

export interface SmsOpPayments {
  amount: Numeric;
  id: Generated<string>;
  invoice_id: string;
  notes: string | null;
  payment_date: Generated<Timestamp>;
  payment_method: string;
  recorded_by_staff_id: string | null;
  transaction_reference: string | null;
}

export interface SmsOpRefunds {
  amount: Numeric;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  invoice_id: string;
  payment_id: string;
  processed_by_staff_id: string | null;
  reason: string | null;
  refund_date: Generated<Timestamp>;
  refund_method: string | null;
}

export interface SmsOpSessionAttendance {
  client_id: string;
  created_at: Generated<Timestamp>;
  notes: string | null;
  recorded_by_staff_id: string | null;
  session_id: string;
  status: string;
  updated_at: Generated<Timestamp>;
}

export interface SmsOpSessions {
  course_offering_id: string;
  created_at: Generated<Timestamp>;
  end_time: Timestamp;
  id: Generated<string>;
  location_id: string | null;
  start_time: Timestamp;
  status: Generated<string>;
  subject_id: string;
  updated_at: Generated<Timestamp>;
}

export interface SmsOpSessionTrainers {
  is_lead_trainer: Generated<boolean>;
  session_id: string;
  staff_id: string;
}

export interface SmsOpStaff {
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  position: string | null;
  staff_number: string | null;
  user_id: string;
}

export interface StorageBuckets {
  allowed_mime_types: string[] | null;
  avif_autodetection: Generated<boolean | null>;
  created_at: Generated<Timestamp | null>;
  file_size_limit: Int8 | null;
  id: string;
  name: string;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  public: Generated<boolean | null>;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageBucketsAnalytics {
  created_at: Generated<Timestamp>;
  format: Generated<string>;
  id: string;
  type: Generated<StorageBuckettype>;
  updated_at: Generated<Timestamp>;
}

export interface StorageIcebergNamespaces {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  updated_at: Generated<Timestamp>;
}

export interface StorageIcebergTables {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  location: string;
  name: string;
  namespace_id: string;
  updated_at: Generated<Timestamp>;
}

export interface StorageMigrations {
  executed_at: Generated<Timestamp | null>;
  hash: string;
  id: number;
  name: string;
}

export interface StorageObjects {
  bucket_id: string | null;
  created_at: Generated<Timestamp | null>;
  id: Generated<string>;
  last_accessed_at: Generated<Timestamp | null>;
  level: number | null;
  metadata: Json | null;
  name: string | null;
  /**
   * Field is deprecated, use owner_id instead
   */
  owner: string | null;
  owner_id: string | null;
  path_tokens: Generated<string[] | null>;
  updated_at: Generated<Timestamp | null>;
  user_metadata: Json | null;
  version: string | null;
}

export interface StoragePrefixes {
  bucket_id: string;
  created_at: Generated<Timestamp | null>;
  level: Generated<number>;
  name: string;
  updated_at: Generated<Timestamp | null>;
}

export interface StorageS3MultipartUploads {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  id: string;
  in_progress_size: Generated<Int8>;
  key: string;
  owner_id: string | null;
  upload_signature: string;
  user_metadata: Json | null;
  version: string;
}

export interface StorageS3MultipartUploadsParts {
  bucket_id: string;
  created_at: Generated<Timestamp>;
  etag: string;
  id: Generated<string>;
  key: string;
  owner_id: string | null;
  part_number: number;
  size: Generated<Int8>;
  upload_id: string;
  version: string;
}

export interface SupabaseFunctionsHooks {
  created_at: Generated<Timestamp>;
  hook_name: string;
  hook_table_id: number;
  id: Generated<Int8>;
  request_id: Int8 | null;
}

export interface SupabaseFunctionsMigrations {
  inserted_at: Generated<Timestamp>;
  version: string;
}

export interface SupabaseMigrationsSchemaMigrations {
  name: string | null;
  statements: string[] | null;
  version: string;
}

export interface SupabaseMigrationsSeedFiles {
  hash: string;
  path: string;
}

export interface VaultDecryptedSecrets {
  created_at: Timestamp | null;
  decrypted_secret: string | null;
  description: string | null;
  id: string | null;
  key_id: string | null;
  name: string | null;
  nonce: Buffer | null;
  secret: string | null;
  updated_at: Timestamp | null;
}

export interface VaultSecrets {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  key_id: string | null;
  name: string | null;
  nonce: Generated<Buffer | null>;
  secret: string;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  "_realtime.extensions": _RealtimeExtensions;
  "_realtime.schema_migrations": _RealtimeSchemaMigrations;
  "_realtime.tenants": _RealtimeTenants;
  "auth.audit_log_entries": AuthAuditLogEntries;
  "auth.flow_state": AuthFlowState;
  "auth.identities": AuthIdentities;
  "auth.instances": AuthInstances;
  "auth.mfa_amr_claims": AuthMfaAmrClaims;
  "auth.mfa_challenges": AuthMfaChallenges;
  "auth.mfa_factors": AuthMfaFactors;
  "auth.oauth_clients": AuthOauthClients;
  "auth.one_time_tokens": AuthOneTimeTokens;
  "auth.refresh_tokens": AuthRefreshTokens;
  "auth.saml_providers": AuthSamlProviders;
  "auth.saml_relay_states": AuthSamlRelayStates;
  "auth.schema_migrations": AuthSchemaMigrations;
  "auth.sessions": AuthSessions;
  "auth.sso_domains": AuthSsoDomains;
  "auth.sso_providers": AuthSsoProviders;
  "auth.users": AuthUsers;
  "avetmiss_submissions.snapshot_nat00010": AvetmissSubmissionsSnapshotNat00010;
  "avetmiss_submissions.snapshot_nat00020": AvetmissSubmissionsSnapshotNat00020;
  "avetmiss_submissions.snapshot_nat00120": AvetmissSubmissionsSnapshotNat00120;
  "avetmiss_submissions.submissions": AvetmissSubmissionsSubmissions;
  "avetmiss.client_avetmiss_details": AvetmissClientAvetmissDetails;
  "avetmiss.client_disabilities": AvetmissClientDisabilities;
  "avetmiss.client_prior_achievements": AvetmissClientPriorAchievements;
  "avetmiss.codes": AvetmissCodes;
  "avetmiss.program_avetmiss_details": AvetmissProgramAvetmissDetails;
  "avetmiss.program_completions": AvetmissProgramCompletions;
  "avetmiss.subject_avetmiss_details": AvetmissSubjectAvetmissDetails;
  "avetmiss.training_activities": AvetmissTrainingActivities;
  "core.addresses": CoreAddresses;
  "core.agents": CoreAgents;
  "core.client_addresses": CoreClientAddresses;
  "core.client_notes": CoreClientNotes;
  "core.clients": CoreClients;
  "core.clients_audit": CoreClientsAudit;
  "core.locations": CoreLocations;
  "core.organisations": CoreOrganisations;
  "core.program_course_plan_subjects": CoreProgramCoursePlanSubjects;
  "core.program_course_plans": CoreProgramCoursePlans;
  "core.program_schedule_units": CoreProgramScheduleUnits;
  "core.program_schedules": CoreProgramSchedules;
  "core.program_subjects": CoreProgramSubjects;
  "core.programs": CorePrograms;
  "core.subject_prerequisites": CoreSubjectPrerequisites;
  "core.subjects": CoreSubjects;
  "cricos.client_details": CricosClientDetails;
  "cricos.confirmations_of_enrolment": CricosConfirmationsOfEnrolment;
  "extensions.pg_stat_statements": ExtensionsPgStatStatements;
  "extensions.pg_stat_statements_info": ExtensionsPgStatStatementsInfo;
  "net._http_response": NetHttpResponse;
  "net.http_request_queue": NetHttpRequestQueue;
  "realtime.messages": RealtimeMessages;
  "realtime.schema_migrations": RealtimeSchemaMigrations;
  "realtime.subscription": RealtimeSubscription;
  "security.roles": SecurityRoles;
  "security.user_roles": SecurityUserRoles;
  "security.users": SecurityUsers;
  "sms_op.agent_commissions": SmsOpAgentCommissions;
  "sms_op.application_documents": SmsOpApplicationDocuments;
  "sms_op.applications": SmsOpApplications;
  "sms_op.assessment_submissions": SmsOpAssessmentSubmissions;
  "sms_op.assessment_tasks": SmsOpAssessmentTasks;
  "sms_op.course_offerings": SmsOpCourseOfferings;
  "sms_op.enrolment_subject_outcomes": SmsOpEnrolmentSubjectOutcomes;
  "sms_op.enrolment_subjects": SmsOpEnrolmentSubjects;
  "sms_op.enrolments": SmsOpEnrolments;
  "sms_op.invoice_line_items": SmsOpInvoiceLineItems;
  "sms_op.invoices": SmsOpInvoices;
  "sms_op.outcomes_audit": SmsOpOutcomesAudit;
  "sms_op.payment_plan_instalments": SmsOpPaymentPlanInstalments;
  "sms_op.payment_plan_template_instalments": SmsOpPaymentPlanTemplateInstalments;
  "sms_op.payment_plan_templates": SmsOpPaymentPlanTemplates;
  "sms_op.payment_plans": SmsOpPaymentPlans;
  "sms_op.payments": SmsOpPayments;
  "sms_op.refunds": SmsOpRefunds;
  "sms_op.session_attendance": SmsOpSessionAttendance;
  "sms_op.session_trainers": SmsOpSessionTrainers;
  "sms_op.sessions": SmsOpSessions;
  "sms_op.staff": SmsOpStaff;
  "storage.buckets": StorageBuckets;
  "storage.buckets_analytics": StorageBucketsAnalytics;
  "storage.iceberg_namespaces": StorageIcebergNamespaces;
  "storage.iceberg_tables": StorageIcebergTables;
  "storage.migrations": StorageMigrations;
  "storage.objects": StorageObjects;
  "storage.prefixes": StoragePrefixes;
  "storage.s3_multipart_uploads": StorageS3MultipartUploads;
  "storage.s3_multipart_uploads_parts": StorageS3MultipartUploadsParts;
  "supabase_functions.hooks": SupabaseFunctionsHooks;
  "supabase_functions.migrations": SupabaseFunctionsMigrations;
  "supabase_migrations.schema_migrations": SupabaseMigrationsSchemaMigrations;
  "supabase_migrations.seed_files": SupabaseMigrationsSeedFiles;
  "vault.decrypted_secrets": VaultDecryptedSecrets;
  "vault.secrets": VaultSecrets;
}
