BEGIN;

-- ============================================
-- Indexes for Master Filter System Performance
-- ============================================
-- These indexes optimize queries generated by the filter system
-- Based on commonly filtered columns identified in the domain map

-- ============================================
-- STUDENTS TABLE INDEXES
-- ============================================

-- Status filtering (very common)
CREATE INDEX IF NOT EXISTS idx_students_status ON public.students(status);

-- Display ID filtering (common for search)
CREATE INDEX IF NOT EXISTS idx_students_display_id ON public.students(student_id_display);

-- Name filtering (common for search)
CREATE INDEX IF NOT EXISTS idx_students_first_name ON public.students(first_name);
CREATE INDEX IF NOT EXISTS idx_students_last_name ON public.students(last_name);

-- Email filtering (common for search)
CREATE INDEX IF NOT EXISTS idx_students_email ON public.students(email);

-- Date filtering
CREATE INDEX IF NOT EXISTS idx_students_created_at ON public.students(created_at);
CREATE INDEX IF NOT EXISTS idx_students_date_of_birth ON public.students(date_of_birth);

-- Foreign key indexes (for joins)
CREATE INDEX IF NOT EXISTS idx_students_application_id ON public.students(application_id);
CREATE INDEX IF NOT EXISTS idx_students_rto_id ON public.students(rto_id);

-- ============================================
-- APPLICATIONS TABLE INDEXES
-- ============================================

-- Status filtering (very common)
CREATE INDEX IF NOT EXISTS idx_applications_status ON public.applications(status);

-- Display ID filtering
CREATE INDEX IF NOT EXISTS idx_applications_display_id ON public.applications(application_id_display);

-- Name filtering
CREATE INDEX IF NOT EXISTS idx_applications_first_name ON public.applications(first_name);
CREATE INDEX IF NOT EXISTS idx_applications_last_name ON public.applications(last_name);

-- Email filtering
CREATE INDEX IF NOT EXISTS idx_applications_email ON public.applications(email);

-- Date filtering
CREATE INDEX IF NOT EXISTS idx_applications_created_at ON public.applications(created_at);
CREATE INDEX IF NOT EXISTS idx_applications_updated_at ON public.applications(updated_at);
CREATE INDEX IF NOT EXISTS idx_applications_offer_generated_at ON public.applications(offer_generated_at);
CREATE INDEX IF NOT EXISTS idx_applications_requested_start_date ON public.applications(requested_start_date);

-- Boolean filtering
CREATE INDEX IF NOT EXISTS idx_applications_is_international ON public.applications(is_international);

-- Foreign key indexes
CREATE INDEX IF NOT EXISTS idx_applications_agent_id ON public.applications(agent_id);
CREATE INDEX IF NOT EXISTS idx_applications_program_id ON public.applications(program_id);
CREATE INDEX IF NOT EXISTS idx_applications_assigned_to ON public.applications(assigned_to);
CREATE INDEX IF NOT EXISTS idx_applications_rto_id ON public.applications(rto_id);

-- ============================================
-- INVOICES TABLE INDEXES
-- ============================================

-- Status filtering (very common)
CREATE INDEX IF NOT EXISTS idx_invoices_status ON public.invoices(status);

-- Invoice number filtering
CREATE INDEX IF NOT EXISTS idx_invoices_invoice_number ON public.invoices(invoice_number);

-- Date filtering
CREATE INDEX IF NOT EXISTS idx_invoices_issue_date ON public.invoices(issue_date);
CREATE INDEX IF NOT EXISTS idx_invoices_due_date ON public.invoices(due_date);
CREATE INDEX IF NOT EXISTS idx_invoices_last_email_sent_at ON public.invoices(last_email_sent_at);

-- Amount filtering (for range queries)
CREATE INDEX IF NOT EXISTS idx_invoices_amount_due_cents ON public.invoices(amount_due_cents);
CREATE INDEX IF NOT EXISTS idx_invoices_amount_paid_cents ON public.invoices(amount_paid_cents);

-- Foreign key indexes
CREATE INDEX IF NOT EXISTS idx_invoices_enrollment_id ON public.invoices(enrollment_id);
CREATE INDEX IF NOT EXISTS idx_invoices_rto_id ON public.invoices(rto_id);

-- ============================================
-- ENROLLMENTS TABLE INDEXES
-- ============================================

-- Status filtering
CREATE INDEX IF NOT EXISTS idx_enrollments_status ON public.enrollments(status);

-- Date filtering
CREATE INDEX IF NOT EXISTS idx_enrollments_commencement_date ON public.enrollments(commencement_date);
CREATE INDEX IF NOT EXISTS idx_enrollments_expected_completion_date ON public.enrollments(expected_completion_date);

-- Foreign key indexes
CREATE INDEX IF NOT EXISTS idx_enrollments_student_id ON public.enrollments(student_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_program_id ON public.enrollments(program_id);
CREATE INDEX IF NOT EXISTS idx_enrollments_rto_id ON public.enrollments(rto_id);

-- ============================================
-- AGENTS TABLE INDEXES
-- ============================================

-- Name filtering (common for search)
CREATE INDEX IF NOT EXISTS idx_agents_name ON public.agents(name);

-- Foreign key indexes
CREATE INDEX IF NOT EXISTS idx_agents_rto_id ON public.agents(rto_id);

-- ============================================
-- PROGRAMS TABLE INDEXES
-- ============================================

-- Name filtering (common for search)
CREATE INDEX IF NOT EXISTS idx_programs_name ON public.programs(name);

-- Code filtering (common for search)
CREATE INDEX IF NOT EXISTS idx_programs_code ON public.programs(code);

-- Foreign key indexes
CREATE INDEX IF NOT EXISTS idx_programs_rto_id ON public.programs(rto_id);

-- ============================================
-- COMPOSITE INDEXES (for multi-column filters)
-- ============================================

-- Students: Status + Created At (common combination)
CREATE INDEX IF NOT EXISTS idx_students_status_created_at ON public.students(status, created_at);

-- Applications: Status + Created At
CREATE INDEX IF NOT EXISTS idx_applications_status_created_at ON public.applications(status, created_at);

-- Invoices: Status + Due Date (for overdue queries)
CREATE INDEX IF NOT EXISTS idx_invoices_status_due_date ON public.invoices(status, due_date);

-- Invoices: Enrollment ID + Status (for student invoice queries)
CREATE INDEX IF NOT EXISTS idx_invoices_enrollment_status ON public.invoices(enrollment_id, status);

COMMIT;


